name: Build Go app and push to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.4



    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Test
      run: go test
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: golang-webhook
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}